spring:
  datasource:
    url: jdbc:h2:mem:rss
    username: test
    password: test
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        # https://github.com/habuma/spring-in-action-6-samples/issues/7
        "[globally_quoted_identifiers]": true
        "[globally_quoted_identifiers_skip_column_definitions]": true
  h2:
    console:
      enabled: true
